import { createAsyncThunk, createSlice } from "@reduxjs/toolkit";
import axios from "axios";

// backend response in the form of hashmap
// with key as date and value as min-nightly-rates.
interface DataState {
  [date: string]: number;
}

interface State {
  data: DataState;
}

// initialState for the slice.
const initialState: State = {
  data: {},
};

// async thunk to get the calendar data from 
// the backend.
export const fetchCalendarData = createAsyncThunk(
  "calendarData/fetchCalendarData",
  async (req, thunkApi) => {
    const respone = await axios.get(
      "https://95xedsf044.execute-api.ap-south-1.amazonaws.com/dev/api/v1/graphql/getDailyRates/4",
      {
        params: {
          startTime: `"2023-03-01T00:00:00.000Z"`,
          endTime: `"2023-05-31T00:00:00.000Z"`,
        },
      }
    );
    return respone.data;
  }
);

export const calendarDataSlice = createSlice({
  name: "calendar",
  initialState,
  reducers: {},
  extraReducers: (builder) => {
    builder.addCase(fetchCalendarData.fulfilled, (state, action) => {
      state.data = action.payload;
    });
  },
});

// exporting the reducer function generated by the slice
export default calendarDataSlice.reducer;
