import { createSlice } from "@reduxjs/toolkit";
// importing RoomType interface from a different module
import { RoomType } from "./roomResultConfigDataSlice"; 

// defining the Checkout interface 
interface Checkout {
  room: RoomType; // a RoomType object containing information about the selected room
  showItineraryCard: boolean; // a boolean flag indicating whether to show the itinerary card or not
}

// defining the initial state of the Checkout object
const initialState: Checkout = {
  room: {
    areaInSquareFeet: 0,
    doubleBed: 0,
    maxCapacity: 0,
    roomTypeName: "",
    roomTypeId: 0,
    propertyAddress: "",
    singleBed: 0,
    roomRate: 0,
    bedType: "",
    priceType: "",
  },
  showItineraryCard: false,
};

// creating the checkoutDataSlice using createSlice method
export const checkoutDataSlice = createSlice({
  name: "checkoutDataSlice", // name of the slice
  initialState, // initial state object
  reducers: {
    // reducer to set the selected room in the state
    setCheckoutRoom: (state, action) => {
      state.room = action.payload; // update the room object in the state with the payload data
    },
    // reducer to toggle the showItineraryCard flag in the state
    setShowItineraryCard: (state, action) => {
      state.showItineraryCard = action.payload; // update the showItineraryCard flag with the payload data
    },
  },
});

// exporting the actions generated by the slice
export const { setShowItineraryCard, setCheckoutRoom } = checkoutDataSlice.actions;

// exporting the reducer function generated by the slice
export default checkoutDataSlice.reducer;
