import { createSlice } from "@reduxjs/toolkit";
import { Promotion } from "../../constants/types";
// importing RoomType interface from a different module
import { RoomType } from "./roomResultConfigDataSlice";

// defining the Checkout interface
interface Checkout {
  room: RoomType; // a RoomType object containing information about the selected room
  showItineraryCard: boolean; // a boolean flag indicating whether to show the itinerary card or not
  selectedPromotion: Promotion;
  guestTypes: {
    categoryName: string;
    ageRange: string;
    show: boolean;
    count: number;
    minCount: number;
  }[];
  startDate: string;
  endDate: string;
  selectedRoom: number;
  vat: number;
  dueNow: number;
  dueAtResort: number;
  taxes: {
    name: string;
    value: number;
  }[];
}

// defining the initial state of the Checkout object
const initialState: Checkout = {
  room: {
    areaInSquareFeet: 0,
    doubleBed: 0,
    maxCapacity: 0,
    roomTypeName: "",
    roomTypeId: 0,
    propertyAddress: "",
    singleBed: 0,
    roomRate: 0,
    bedType: "",
    priceType: "",
    bestPromotion: {
      minimumDaysOfStay: 0,
      priceFactor: 0,
      promotionDescription: "",
      promotionTitle: "",
      isDeactivated: false,
      promotionId: 0,
    },
    ratingAndReviews: {
      showRatingsAndReviews: true,
      averageRatingValue: 0,
      numberOfRatings: 0,
    },
  },
  selectedPromotion: {
    minimumDaysOfStay: NaN,
    priceFactor: NaN,
    promotionDescription: "",
    promotionTitle: "",
    isDeactivated: false,
    promotionId: NaN,
  },
  showItineraryCard: false,
  guestTypes: [],
  startDate: "",
  endDate: "",
  selectedRoom: 0,
  vat: 0,
  dueAtResort: 0,
  dueNow: 0,
  taxes: [],
};

// creating the checkoutDataSlice using createSlice method
export const checkoutDataSlice = createSlice({
  name: "checkoutDataSlice", // name of the slice
  initialState, // initial state object
  reducers: {
    // reducer to set the selected room in the state
    setCheckoutRoom: (state, action) => {
      state.room = action.payload; // update the room object in the state with the payload data
    },
    // reducer to toggle the showItineraryCard flag in the state
    setShowItineraryCard: (state, action) => {
      state.showItineraryCard = action.payload; // update the showItineraryCard flag with the payload data
    },
    setSelectedPromotion: (state, action) => {
      state.selectedPromotion = action.payload;
    },
    setSelectedGuestType: (state, action) => {
      state.guestTypes = action.payload;
    },
    setDates: (state, action) => {
      state.startDate = action.payload.startDate;
      state.endDate = action.payload.endDate;
    },
    setCheckoutSelectedRoom: (state, action) => {
      state.selectedRoom = action.payload;
    },
  },
});

// exporting the actions generated by the slice
export const {
  setShowItineraryCard,
  setCheckoutRoom,
  setSelectedPromotion,
  setSelectedGuestType,
  setDates,
  setCheckoutSelectedRoom,
} = checkoutDataSlice.actions;

// exporting the reducer function generated by the slice
export default checkoutDataSlice.reducer;
