import { createSlice } from "@reduxjs/toolkit";

// defining the Language interface
interface Language {
  selectedLanguage: string; // a string representing the user's selected language
  supportedLanguage: string[]; // an array of supported language codes
}

// defining the initial state of the Language object
const initialState: Language = {
  selectedLanguage: "",
  supportedLanguage: ["en", "fr"],
};

// creating the languageDataSlice using createSlice method
export const languageDataSlice = createSlice({
  name: "language", // name of the slice
  initialState, // initial state object
  reducers: {
    // reducer to set the selected language in the state
    setSelectedLanguage: (state, action) => {
      state.selectedLanguage = action.payload; // update the selectedLanguage property in the state with the payload data
    },
  },
});

// exporting the reducer function generated by the slice
export default languageDataSlice.reducer;

// exporting the actions generated by the slice
export const { setSelectedLanguage } = languageDataSlice.actions;
